### ISSUE TITLE
ubuntu 16.04 build error

### ISSUE THREAD

**Issue by cn0xroot** [luigifcruz/CyberRadio#2]
Hi lucas,this project is great.
But when I try to build it on ubuntu ,something error:

```
sudo pip3 install -r requirements.txt
WARNING: The directory '/home/init3/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/luigifreitas/fbs.git@ubuntu_16.04 (from -r requirements.txt (line 6))
  Cloning https://github.com/luigifreitas/fbs.git (to revision ubuntu_16.04) to /tmp/pip-req-build-18ln1zci
  Running command git clone -q https://github.com/luigifreitas/fbs.git /tmp/pip-req-build-18ln1zci
  Running command git checkout -b ubuntu_16.04 --track origin/ubuntu_16.04
  切换到一个新分支 'ubuntu_16.04'
  分支 'ubuntu_16.04' 设置为跟踪来自 'origin' 的远程分支 'ubuntu_16.04'。
Collecting git+https://github.com/luigifreitas/radio-core.git (from -r requirements.txt (line 7))
  Cloning https://github.com/luigifreitas/radio-core.git to /tmp/pip-req-build-ieoabdui
  Running command git clone -q https://github.com/luigifreitas/radio-core.git /tmp/pip-req-build-ieoabdui
Collecting numba
  Downloading numba-0.47.0-cp35-cp35m-manylinux1_x86_64.whl (3.7 MB)
     |████████████████████████████████| 3.7 MB 10.8 MB/s 
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2)) (1.15.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3)) (1.2.0rc1)
Collecting sounddevice
  Downloading sounddevice-0.3.14-py2.py3-none-any.whl (30 kB)
Requirement already satisfied: pyqt5 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 5)) (5.10.1)
Collecting PyInstaller>=3.3
  Downloading PyInstaller-3.6.tar.gz (3.5 MB)
     |████████████████████████████████| 3.5 MB 5.7 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpipuohgua
       cwd: /tmp/pip-install-z3m_wt8k/PyInstaller
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 85, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 76, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpipuohgua Check the logs for full command output.
```
```
OS:Ubuntu 16.04.6 LTS 64 bit
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
```
Any idea to fix this error?
Thanks!

**Comment by luigifcruz** [comment]
Hey, thanks for trying CyberRadio! This [comment](https://github.com/pypa/setuptools/issues/1694#issuecomment-466023567) suggests a fix for this error on the setuptools repository.

**Comment by cn0xroot** [comment]
Thanks for your quilk reply.
It works fine now,after upgrade setuptool.

Have a nice day!
